### PR TITLE
removing tests and benchmarks

### PR DESCRIPTION
**Pull request by JPZV**
Due to the path limit on Windows, I'd recommend to remove the test_and_benchmark directory, as this repository is used only for BlueRetro, and having that directory would difficult to contribute for Windows User without some shadow workarounds.

I don't think don't having those tests and benchmarks would affect at all to BlueRetro.

For more info, please refer to [this issue](https://github.com/darthcloud/BlueRetro/issues/522)

### CODE REVIEW

**Comment by darthcloud** [comment]
I use windows everyday and have no issue.

**Comment by darthcloud** [comment]
Did you install esp-idf using the powershell script?

**Comment by JPZV** [comment]
Maybe if you have the repository on root of your drive (i.e. C:\, D:\, etc.) it wouldn't happen because the limit wouldn't reach while cloning. But for someone like me that have its own folder for Git repositories inside the Documents folder, it's a real problem because of the loooooooong name for the benchmarks.

Every time I try to clone BlueRetro, it fails with this message:

`liblfds7.1.1/test_and_benchmark/libbenchmark/src/libbenchmark_benchmarks_queue_umm_enqueue1_then_dequeue1/libbenchmark_benchmarks_queue_umm_pthread_spinlock_process_private_enqueue1_dequeue1.c: Filename too long`

And that's because the base path is `E:\Users\jpzv\Documents\Git\BlueRetro`, so the full path for that file would become `E:\Users\jpzv\Documents\Git\BlueRetro\components\queue_bss\liblfds\liblfds7.1.1\test_and_benchmark\libbenchmark\src\libbenchmark_benchmarks_queue_umm_enqueue1_then_dequeue1\libbenchmark_benchmarks_queue_umm_pthread_spinlock_process_private_enqueue1_dequeue1.c`


> Did you install esp-idf using the powershell script?

It's not about compiling the project but rather about cloning it with Git/GitHub Desktop

**Comment by darthcloud** [comment]
No i'm in my user dir.

My windows terminal powershell setting:
WindowsTerminal_h0kFJ8SrMV

And my ps1 script content:
$env:IDF_TOOLS_PATH = "$HOME\ws\idf_202302\"
. $HOME\ws\idf_202302\esp-idf\export.ps1

**Comment by darthcloud** [comment]
The git binary from Git Bash work fine in both bash and PowerShell for me.

**Comment by JPZV** [comment]
This is the output for me on PowerShell:

```
PS E:\Users\jpzv\Documents\Git> git clone --recursive https://github.com/JPZV/BlueRetro
Cloning into 'BlueRetro'...
remote: Enumerating objects: 6463, done.
remote: Counting objects: 100% (469/469), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 6463 (delta 304), reused 451 (delta 291), pack-reused 5994
Receiving objects: 100% (6463/6463), 2.08 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (4931/4931), done.
Submodule 'components/queue_bss/liblfds' (https://github.com/darthcloud/liblfds7.1.1.git) registered for path 'components/queue_bss/liblfds'
Cloning into 'E:/Users/jpzv/Documents/Git/BlueRetro/components/queue_bss/liblfds'...
remote: Enumerating objects: 513, done.
remote: Counting objects: 100% (513/513), done.
remote: Compressing objects: 100% (264/264), done.
remote: Total 513 (delta 236), reused 513 (delta 236), pack-reused 0
Receiving objects: 100% (513/513), 278.57 KiB | 1.70 MiB/s, done.
Resolving deltas: 100% (236/236), done.
error: unable to create file liblfds7.1.1/test_and_benchmark/libbenchmark/src/libbenchmark_benchmarks_queue_umm_enqueue1_then_dequeue1/libbenchmark_benchmarks_queue_umm_pthread_spinlock_process_private_enqueue1_dequeue1.c: Filename too long
fatal: Unable to checkout 'da3494fef10df4681e267d8b2b8cce2c90d5a9fa' in submodule path 'components/queue_bss/liblfds'
PS E:\Users\jpzv\Documents\Git>
```

While in Git Bash is something similar but with Linux-ish style

**Comment by JPZV** [comment]
Steps to reproduce it:

1. Go to C:\Users
2. Create a new Folder (it will ask you some Admin Rights. You don't need to create a true user, just the folder)
3. Name that folder as "blueretro"
4. Inside, create another folder named "Documents" (again with admin rights). And, finally, inside, create a new one called "Git"
5. Open PowerShell (Or Terminal) as Admin, and navigate to `C:\Users\blueretro\Documents\Git`
6. Try to use this command: `git clone --recursive https://github.com/darthcloud/BlueRetro`.
7. After a while, it'll fail with the same error that I showed you before, or at least it should be.

**Comment by darthcloud** [comment]
That did work fine for me.

I do have HKLM\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled set to 1.

**Comment by JPZV** [comment]
I have that key in 1 too. Also the group policy says that it's enabled, but I cannot get it work though.

**Comment by darthcloud** [comment]
I installed the idf using the espressif installer once on my machine:
https://dl.espressif.com/dl/esp-idf/

It auto added a profile in my windows terminal on which I based my handmade profile.

It probably do something to fix path length.

**Comment by JPZV** [comment]
I'm pretty sure that I installed mine using their installer, but that was long ago.

Any way, this issue doesn't stops me to make changes to BlueRetro. I just need to do some workaround. They're annoying but not that hard to do.

And I'm even thinking about moving my entire projects folder to the root of the drive, as I use a dedicated one for personal/work data, so the root is pretty clean by now.

So, because of that, I'll close this PR as I thought it was an issue on every Windows Machine, but it seems it isn't. If another Windows user comes with the same issue, I think it could worth the dispute about removing or not the tests and brenchmarking

**Comment by darthcloud** [comment]
Ultimately if it was my code I wouldn't mind, but since it's not I rather not touch anything.

Especially if their is a way to get it working as-is. But it's not clear what is the way.

**Comment by JPZV** [comment]
> Especially if **their** is a way to get it working as-is. But it's not clear what is the way.

I'm not sure if you meant to say "Their" or "There". But, just in case, my way to get it work as it's right now, is to clone it through Git/GitHub desktop as I'd do normally and let them fail (with the `--recursive` flag). Then, add it to the GitHub Desktop as an existent repository.

The downside about this is that every time I do a change, it appears like there is a modification to liblfds7.1.1 (see screenshot below), and that's because there are some missing files (those with the long name). I can still make changes, commits and push, but I wonder what would happen if you add another submodule to BlueRetro, as right now Gil fails with a "Fatal Error". I'm not sure if it'll ignore liblfds and then proceed with the remaining submodules, or if it'll fail completely leaving with an incomplete clone and a headache

image

**Pull request closed without merging**
